import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { useRef, useEffect, useState } from 'react'

import SecOne from '@/components/landing/SecOne'
import SecTwo from '@/components/landing/SecTwo'
import SecThree from "@/components/landing/SecThree"
import SecFour from "@/components/landing/SecFour"
import SecFive from '@/components/landing/SecFive'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const [isScrolled, setIsScrolled] = useState(false);
  const mainRef = useRef(null);

  useEffect(() => {
    const handleScroll = () => {
      const container = mainRef.current;
      if (container.scrollTop > 0 && !isScrolled) {
        setIsScrolled(true);
        hideBrowserNavigation();
      } else if (container.scrollTop === 0 && isScrolled) {
        setIsScrolled(false);
        showBrowserNavigation();
      }
    };

    const container = mainRef.current;
    container.addEventListener('scroll', handleScroll);

    return () => {
      container.removeEventListener('scroll', handleScroll);
    };
  }, [isScrolled]);

  const hideBrowserNavigation = () => {
    // Hide mobile browser navigation bar
    window.scrollTo(0, 1);
  };

  const showBrowserNavigation = () => {
    // Show mobile browser navigation bar
    window.scrollTo(0, 0);
  };

  return (
    <>
      <Head>
        <title>DS website</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <main ref={mainRef} className={styles.main}>
        <SecOne />
        <SecTwo/>
        <SecThree/>
        <SecFour/>
        <SecFive />
      </main>
       
        


    </>
  )
}
