import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import { useRef, useEffect } from 'react'

import SecOne from '@/components/landing/SecOne'
import SecTwo from '@/components/landing/SecTwo'
import SecThree from "@/components/landing/SecThree"
import SecFour from "@/components/landing/SecFour"
import SecFive from '@/components/landing/SecFive'

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const metaRef = useRef(null);
  const mainRef = useRef(null)

  useEffect(() => {
    function handleScroll() {
      const { body, documentElement } = document;
      const scrollTop = body.scrollTop || documentElement.scrollTop;

      if (scrollTop > 0) {
        metaRef.current.setAttribute('content', 'height=device-height, width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no');
      } else {
        metaRef.current?.setAttribute('content', 'height=device-height, width=device-width, initial-scale=1.0');
      }
    }

    mainRef.current?.addEventListener('scroll', handleScroll);

    return () => {
      mainRef.current.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>DS website</title>
        <meta ref={metaRef} name="viewport" content="height=device-height, width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <main ref={mainRef} className={styles.main}>
        <SecOne />
        <SecTwo/>
        <SecThree/>
        <SecFour/>
        <SecFive />
      </main>
       
        


    </>
  )
}
